[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rirun"
version = "0.2.0"
description = "A Carla runner for creating parametrizable scenarios from real-world automotive scenes"
readme = "README.md"
requires-python = ">=3.8,<3.9"
license = { text = "GPL-3.0 AND MIT AND APACHE-2.0" }

authors = [
  { name = "Bastian Havers-Zulka", email = "bastian.havers-zulka@ri.se" }
]

dependencies = [
  "numpy==1.23.0",
  "pandas==2.0.3",
  "scipy==1.10.1",
  "scikit-learn==1.3.2",
  "torch==2.2.0",
  "torchvision==0.17.0",
  "torchaudio==2.2.0",
  "lightning==2.3.3",
  "hydra-core==1.3.2",
  "omegaconf==2.3.0",
  "opencv-python==4.2.0.32",
  "pillow==10.2.0",
  "transformers==4.46.3",
  "timm==0.9.16",
  "rich_argparse==1.7.2",
  "carla==0.9.15",
  "py_trees==2.2.3",
  "pygame==2.6.1",
  "shapely==2.0.7",
  "ujson==5.10.0",
  "laspy==2.5.4",
  "imgaug==0.4.0",
  "filterpy==1.4.5",
  "rdp==0.8",
  "dataprov @ git+https://github.com/BastianHavers/dataprov.git@feature/py38-compatibility",
]

[project.optional-dependencies]
train = [
  "accelerate==1.0.1",
  "deepspeed==0.16.2",
  "peft==0.13.2",
  "onnx==1.15.0",
]

dev = [
  "black==24.8.0",
  "ruff==0.13.2",
  "ipykernel==6.29.5",
  "line-profiler==4.1.2",
  "wandb==0.21.4",
]

[tool.setuptools]
packages = { find = { where = ["src"] } }

[tool.black]
line-length = 88
target-version = ["py38"]

[tool.ruff]
target-version = "py38"